log:
  loglevel: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 8080
  protocol: trojan
  settings:
    clients:
    - password: "b5330514-a939-49f3-98d6-32b8d2f4068e"
  streamSettings:
    network: ws
    wsSettings:
      path: qwe
  sniffing:
    enabled: false
    destOverride:
    - http
    - tls
    - quic
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
